baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "Peinau Documentation"
theme = "hugo-theme-docdock"
themesdir = "./../themes"


[params]
editURL = "https://github.com/Peinau/hugo-dev-portal/edit/master/site/content/"
showVisitedLinks = false # default is false
themeStyle = "original" # "original" or "flex" # default "original"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = true # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
apiUrl = "https://api.sandbox.connect.fif.tech"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.main]]
name = "<i class='fa fa-github'></i>&nbsp;&nbsp;&nbsp;Seccion2"
identifier = "Seccion2"
url = "http://dev-portal.sandbox.connect.fif.tech/introduction/#1-obtener-un-token-de-acceso"
weight = 40

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i>&nbsp;&nbsp;&nbsp;Github repo"
identifier = "ds"
url = "https://github.com/Peinau/hugo-dev-portal"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i>&nbsp;&nbsp;&nbsp;How to Contribute"
url = "/how-to-contribute"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i>&nbsp;&nbsp;&nbsp;Credits"
url = "/credits"
weight = 30
