baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "Peinau Documentation"
theme = "hugo-theme-docdock"
themesdir = "./../themes"


[params]
editURL = "https://github.com/Peinau/hugo-dev-portal/edit/master/site/content/"
showVisitedLinks = false # default is false
themeStyle = "original" # "original" or "flex" # default "original"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = true # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
apiUrl = "https://api.sandbox.connect.fif.tech"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.main]]
name = "Token"
pre = "<i class='fa fa-road'></i>"
weight = -110
url = "http://dev-portal.sandbox.connect.fif.tech/introduction/#1-obtener-un-token-de-acceso"

